# -*- coding: utf-8 -*-

"""
this module is generated by https://pypi.org/project/tt4human = 0.2.2
"""

from pathlib import Path
from tt4human.api import BetterStrEnum, TruthTable


class WeatherEnum(BetterStrEnum):
    is_sunny = "is_sunny"
    not_sunny = "not_sunny"


class GetUpEnum(BetterStrEnum):
    before_10 = "before_10"
    _10_to_2 = "10_to_2"
    after_2 = "after_2"


truth_table = TruthTable.from_csv(
    path=Path(__file__).absolute().parent.joinpath("do_you_go_out.tsv"),
)

if __name__ == "__main__":
    assert truth_table.evaluate(case={'weather': 'is_sunny', 'get_up': 'before_10'}) is True